# Generated by Django 5.1 on 2024-10-06 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocareweb', '0002_servicecategory_vehiclemake_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotname', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('allocated', 'Allocated'), ('free', 'Free'), ('disabled', 'Disabled')], default='free', max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('mechanic', models.ForeignKey(blank=True, limit_choices_to={'role': 'mechanic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
