# Generated by Django 5.1 on 2024-10-08 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocareweb', '0005_mechanic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='mechanic_id',
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='mechanic_email',
            field=models.OneToOneField(limit_choices_to={'role': 'mechanic'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
