# Generated by Django 5.1 on 2024-10-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocareweb', '0006_remove_mechanic_mechanic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='level',
            field=models.IntegerField(choices=[('senior', 'Senior Level'), ('medium', 'Medium Level'), ('entry', 'Entry Level')], default='entry'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='status',
            field=models.IntegerField(choices=[('working', 'Working'), ('active', 'Active'), ('absentees', 'Absentees')], default='active'),
        ),
    ]
