# Generated by Django 5.1 on 2024-10-09 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocareweb', '0007_alter_mechanic_level_alter_mechanic_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'service_manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_managers', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(limit_choices_to={'role': 'mechanic'}, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_mechanics', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocareweb.slot')),
            ],
            options={
                'unique_together': {('slot', 'mechanic')},
            },
        ),
    ]
