# Generated by Django 5.1 on 2024-10-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocareweb', '0008_allocatedmechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_category_images/'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_type_images/'),
        ),
    ]
