# Generated by Django 5.1 on 2024-10-18 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocareweb', '0010_servicecart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='mechanic_email',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechanic',
            name='mechanic',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
