# Generated by Django 5.1 on 2024-10-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocareweb', '0011_remove_mechanic_mechanic_email_mechanic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='level',
            field=models.IntegerField(choices=[(1, 'Senior Level'), (2, 'Medium Level'), (3, 'Entry Level')], default=3),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='status',
            field=models.IntegerField(choices=[(1, 'Working'), (2, 'Active'), (3, 'Absentees')], default=2),
        ),
    ]
