# Generated by Django 5.1 on 2024-10-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocareweb', '0016_servicecart_cart_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Work in Progress'), ('completed', 'Completed'), ('confirmed', 'Order Confirmed')], default='confirmed', max_length=10),
        ),
    ]
