# Generated by Django 5.1 on 2024-10-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocareweb', '0017_order_service_date_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='allocated_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autocareweb.slot'),
        ),
    ]
