# Generated by Django 5.1 on 2024-10-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocareweb', '0019_alter_slot_mechanic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='mechanic',
        ),
    ]
