# Generated by Django 5.1 on 2024-10-21 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocareweb', '0021_slot_mechanic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocateJuniorMechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('junior_mechanic', models.ForeignKey(limit_choices_to={'role': 'mechanic'}, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_junior_mechanics', to=settings.AUTH_USER_MODEL)),
                ('senior_mechanic', models.ForeignKey(limit_choices_to={'role': 'mechanic'}, on_delete=django.db.models.deletion.CASCADE, related_name='allocating_senior_mechanics', to=settings.AUTH_USER_MODEL)),
                ('service_manager', models.ForeignKey(limit_choices_to={'role': 'service_manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='junior_mechanic_allocations', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocareweb.slot')),
            ],
        ),
    ]
